services:
  - type: web
    name: dashboard
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn analytics-dashboard-assessment.wsgi"
    plan: free  # Optional: Render offers a free plan for small apps
